#!/usr/bin/env python3
"""
stages_from_rbxmx.py — turns a "<Class>_AllStages" model saved from Roblox Studio / Claude Design
(.rbxmx, one Model per merge stage) into a Luau data module the game builds its soldiers from.

Usage:
    python tools/stages_from_rbxmx.py design/Knight_AllStages.rbxmx src/shared/StageModels/Knight.luau

Expected input: a top-level Model that contains one Model per stage (Knight_Stage1 … Knight_Stage9),
each made of anchored Parts (feet on y = 0, facing -Z). Every stage may stand at its own x offset
(they are laid out side by side): the offset is taken from the part named "Hitbox".
The output keeps, per part: name, size, position (relative to the stage), color, material, reflectance,
transparency and shape, and per stage whether it has an aura (PointLight / Sparkles) and how high
the model reaches (`top`, used to place the name label).
"""

import sys
import xml.etree.ElementTree as ET


def text(element, path, default=None):
    node = element.find(path)
    return node.text if node is not None else default


def number(value: float) -> str:
    value = round(value, 4)
    return str(int(value)) if value == int(value) else str(value)


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    source, target = sys.argv[1], sys.argv[2]

    root = ET.parse(source).getroot()
    top = root.find("Item")
    stage_models = [m for m in top.findall("Item") if m.get("class") == "Model"]

    lines = [
        "--!strict",
        f"-- GENERATED by tools/stages_from_rbxmx.py from {source.replace(chr(92), '/').split('/')[-1]}.",
        "-- Do not edit by hand: change the design and run the tool again.",
        "-- One entry per merge stage. Coordinates: feet on y = 0, facing -Z, x = 0 in the middle.",
        "",
        "local V = Vector3.new",
        "local C = Color3.fromRGB",
        "",
        "export type Part = {",
        "\tname: string?,",
        "\tsize: Vector3,",
        "\tposition: Vector3,",
        "\tcolor: Color3,",
        "\tmaterial: number, -- an Enum.Material value",
        "\treflectance: number?,",
        "\ttransparency: number?,",
        "\tshape: number?, -- an Enum.PartType value",
        "}",
        "export type Stage = { top: number, aura: boolean, parts: { Part } }",
        "",
        "local stages: { Stage } = {",
    ]

    for index, model in enumerate(stage_models, start=1):
        parts = model.findall("Item[@class='Part']")
        offset_x = 0.0
        for part in parts:
            if text(part, "Properties/string[@name='Name']") == "Hitbox":
                offset_x = float(text(part, "Properties/CoordinateFrame/X"))
        aura = any(item.get("class") in ("PointLight", "Sparkles") for item in model.iter("Item"))

        rows = []
        head_y = 4.6
        max_y = 0.0
        for part in parts:
            props = part.find("Properties")
            name = text(props, "string[@name='Name']")
            size = [float(text(props, f"Vector3[@name='size']/{axis}")) for axis in "XYZ"]
            frame = props.find("CoordinateFrame")
            position = [float(text(frame, axis)) for axis in "XYZ"]
            position[0] -= offset_x
            packed = int(text(props, "Color3uint8[@name='Color3uint8']"))
            color = ((packed >> 16) & 255, (packed >> 8) & 255, packed & 255)
            material = int(text(props, "token[@name='Material']", "272"))
            reflectance = float(text(props, "float[@name='Reflectance']", "0"))
            transparency = float(text(props, "float[@name='Transparency']", "0"))
            shape = text(props, "token[@name='shape']")

            # The head is the 1.2 cube around y = 4.6 (it carries the name label in the game).
            if name != "Hitbox" and all(abs(s - 1.2) < 0.01 for s in size) and abs(position[1] - head_y) < 0.1:
                name = "Head"
            if name != "Hitbox":
                max_y = max(max_y, position[1] + size[1] / 2)

            fields = []
            if name and name != "Part":
                fields.append(f'name = "{name}"')
            fields.append(f"size = V({', '.join(number(v) for v in size)})")
            fields.append(f"position = V({', '.join(number(v) for v in position)})")
            fields.append(f"color = C({color[0]}, {color[1]}, {color[2]})")
            fields.append(f"material = {material}")
            if reflectance:
                fields.append(f"reflectance = {number(reflectance)}")
            if transparency:
                fields.append(f"transparency = {number(transparency)}")
            if shape is not None:
                fields.append(f"shape = {shape}")
            rows.append("\t\t\t{ " + ", ".join(fields) + " },")

        lines.append(f"\t-- stage {index} ({len(parts)} parts)")
        lines.append("\t{")
        lines.append(f"\t\ttop = {number(max_y - head_y + 0.9)}, -- label height above the head")
        lines.append(f"\t\taura = {'true' if aura else 'false'},")
        lines.append("\t\tparts = {")
        lines.extend(rows)
        lines.append("\t\t},")
        lines.append("\t},")

    lines.append("}")
    lines.append("")
    lines.append("return { stages = stages }")
    lines.append("")

    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"{len(stage_models)} stages, {sum(len(m.findall(chr(73) + 'tem[@class=' + chr(39) + 'Part' + chr(39) + ']')) for m in stage_models)} parts -> {target}")


if __name__ == "__main__":
    main()
