#!/usr/bin/env python3
"""
rings_from_rbxmx.py — turns the designed battle-ring auras (.rbxmx: a Model with one "BattleRing_<Rarity>"
model per rarity, each with an "Aura" model) into a Luau data module the game builds the auras of the squad
pads from.

Usage:
    python tools/rings_from_rbxmx.py design/BattleRing_Auras.rbxmx src/server/Services/DecorData/BattleRingAuras.luau

Only the Aura of every rarity is stored (the ring itself is the game's fight slot). Every aura part is relative
to the ring: x / z from the middle of the ring's "Base", y from the floor (the bottom of the Base). Per part:
name, size, cf (relative CFrame), color, material, transparency, shape, the group it spins with ("Runes",
"RunesB", "Orbs" or "" = still), and an optional PointLight / ParticleEmitter.
"""

import sys
import xml.etree.ElementTree as ET


def text(element, path, default=None):
    node = element.find(path)
    return node.text if node is not None else default


def number(value: float) -> str:
    value = round(value, 4)
    if value == 0:
        return "0"
    return str(int(value)) if value == int(value) else str(value)


def rgb_float(element):
    return tuple(round(float(element.find(a).text) * 255) for a in "RGB")


def color_packed(packed: int):
    return ((packed >> 16) & 255, (packed >> 8) & 255, packed & 255)


def sequence_numbers(raw: str):
    return [float(v) for v in raw.split()]


def color_sequence(raw: str) -> str:
    values = sequence_numbers(raw)
    keys = []
    for i in range(0, len(values), 5):
        t, r, g, b = values[i:i + 4]
        keys.append(f"ColorSequenceKeypoint.new({number(t)}, Color3.new({number(r)}, {number(g)}, {number(b)}))")
    return "ColorSequence.new({ " + ", ".join(keys) + " })"


def number_sequence(raw: str) -> str:
    values = sequence_numbers(raw)
    keys = []
    for i in range(0, len(values), 3):
        t, v, e = values[i:i + 3]
        keys.append(f"NumberSequenceKeypoint.new({number(t)}, {number(v)}, {number(e)})")
    return "NumberSequence.new({ " + ", ".join(keys) + " })"


def number_range(raw: str) -> str:
    values = sequence_numbers(raw)
    return f"NumberRange.new({number(values[0])}, {number(values[-1])})"


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    source, target = sys.argv[1], sys.argv[2]
    top = ET.parse(source).getroot().find("Item")

    out = [
        "--!strict",
        f"-- GENERATED by tools/rings_from_rbxmx.py from {source.replace(chr(92), '/').split('/')[-1]}.",
        "-- Do not edit by hand: change the design and run the tool again.",
        "-- The aura of a squad pad per rarity. Every part is relative to the ring (middle of the ring, floor level).",
        "",
        "local V = Vector3.new",
        "local C = Color3.fromRGB",
        "local CF = CFrame.new",
        "",
        "return {",
    ]
    for ring in top.findall("Item[@class='Model']"):
        name = text(ring, "Properties/string[@name='Name']")
        rarity = name.replace("BattleRing_", "")
        base = None
        for part in ring.findall("Item[@class='Part']"):
            if text(part, "Properties/string[@name='Name']") == "Base":
                base = part
        frame = base.find("Properties/CoordinateFrame")
        bx, bz = float(frame.find("X").text), float(frame.find("Z").text)
        aura = None
        for model in ring.findall("Item[@class='Model']"):
            if text(model, "Properties/string[@name='Name']") == "Aura":
                aura = model
        out.append(f"\t{rarity} = {{")

        def emit(part, group):
            props = part.find("Properties")

            def prop(tag, name, default=None):
                return text(props, tag + "[@name='" + name + "']", default)

            cf = props.find("CoordinateFrame")
            x, y, z = (float(cf.find(a).text) for a in "XYZ")
            rot = [float(cf.find(a).text) for a in ["R00", "R01", "R02", "R10", "R11", "R12", "R20", "R21", "R22"]]
            size = [float(props.find("Vector3[@name='size']/" + a).text) for a in "XYZ"]
            color = color_packed(int(prop("Color3uint8", "Color3uint8")))
            part_name = prop("string", "Name")
            fields = [
                'name = "' + part_name + '"',
                'group = "' + group + '"',
                "size = V(" + ", ".join(number(v) for v in size) + ")",
                "cf = CF(" + ", ".join([number(x - bx), number(y), number(z - bz)] + [number(v) for v in rot]) + ")",
                "color = C(%d, %d, %d)" % color,
                "material = " + prop("token", "Material", "272"),
            ]
            transparency = float(prop("float", "Transparency", "0"))
            if transparency:
                fields.append("transparency = " + number(transparency))
            shape = prop("token", "shape")
            if shape is not None:
                fields.append("shape = " + shape)
            for child in part.findall("Item"):
                cprops = child.find("Properties")

                def cprop(tag, name, default=None):
                    return text(cprops, tag + "[@name='" + name + "']", default)

                if child.get("class") == "PointLight":
                    c = rgb_float(cprops.find("Color3[@name='Color']"))
                    fields.append("light = { color = C(%d, %d, %d), brightness = %s, range = %s }" % (c[0], c[1], c[2], number(float(cprop("float", "Brightness", "1"))), number(float(cprop("float", "Range", "8")))))
                elif child.get("class") == "ParticleEmitter":
                    e = [
                        "color = " + color_sequence(cprop("ColorSequence", "Color")),
                        "size = " + number_sequence(cprop("NumberSequence", "Size")),
                        "transparency = " + number_sequence(cprop("NumberSequence", "Transparency")),
                        "lifetime = " + number_range(cprop("NumberRange", "Lifetime")),
                        "speed = " + number_range(cprop("NumberRange", "Speed")),
                        "rate = " + number(float(cprop("float", "Rate", "10"))),
                        "lightEmission = " + number(float(cprop("float", "LightEmission", "0"))),
                        'texture = "' + (text(cprops, "Content[@name='Texture']/url", "") or "") + '"',
                    ]
                    fields.append("emitter = { " + ", ".join(e) + " }")
            out.append("		{ " + ", ".join(fields) + " },")

        for child in aura.findall("Item"):
            if child.get("class") == "Part":
                emit(child, "")
            elif child.get("class") == "Model":
                group = text(child, "Properties/string[@name='Name']")
                for part in child.findall("Item[@class='Part']"):
                    emit(part, group)
        out.append("\t},")
    out.append("}")
    out.append("")
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out))
    print(f"-> {target}")


if __name__ == "__main__":
    main()
